array_width = 111
attr_fn_like_width = 111
# blank_lines_upper_bound = 2
# combine_control_expr = false
# comment_width = 100
edition = "2021"
fn_call_width = 111
hard_tabs = true
# imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
max_width = 111
# imports_granularity = "Module"
newline_style = "Unix"
# reorder_impl_items = true
# group_imports = "StdExternalCrate"
single_line_if_else_max_width = 0
# where_single_line = true
# wrap_comments = true